### PR TITLE
fix: assign map to rawState when it is nil to prevent panic

### LINKED ISSUE #176: docker_container's State Migration from v1 to v2 raises panic (assignment to entry in nil map)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I think that I've stumbled up on a bug. 

I'm updating a repository which was build with terraform 0.12 and terraform/docker 2.6. I'm trying to update it to terraform 0.14 and kreuzwerker/terraform-provider-docker 2.11.0

I was able to get it all working with terraform 0.13 and terraform/docker 2.6, but the second I update terraform/docker to 2.7 I get a:
```
2021-04-12T18:57:16.111+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:57:16.441+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Canceled desc = context canceled

2021-04-12T18:57:16.597+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:57:16.597+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:57:16.597+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:57:16.598+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

Updating to kreuzwerker/terraform-provider-docker 2.11.0 doesn't help. I keep getting that error.

I first thought that the problem is in the container image name as we were providing a string and not an id. I changed all docker_container blocks to actually load docker_image.image_name.latest.

I sometimes managed to get a Terraform crash and in the crash I see this:

```
2021/04/12 18:47:36 [TRACE] Completed graph transform *terraform.ResourceCountTransformer with new graph:
  docker_image.watch - *terraform.NodePlannableResourceInstance
  ------
2021/04/12 18:47:36 [TRACE] Executing graph transform *terraform.OrphanResourceInstanceCountTransformer
2021/04/12 18:47:36 [TRACE] Completed graph transform *terraform.OrphanResourceInstanceCountTransformer (no changes)
2021/04/12 18:47:36 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2021/04/12 18:47:36 [DEBUG] Resource instance state not found for node "docker_image.watch", instance docker_image.watch
2021/04/12 18:47:36 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2021/04/12 18:47:36 [TRACE] Executing graph transform *terraform.TargetsTransformer
2021/04/12 18:47:36 [TRACE] Completed graph transform *terraform.TargetsTransformer (no changes)
2021/04/12 18:47:36 [TRACE] Executing graph transform *terraform.ReferenceTransformer
2021/04/12 18:47:36 [DEBUG] ReferenceTransformer: "docker_image.watch" references: []
2021/04/12 18:47:36 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2021/04/12 18:47:36 [TRACE] Executing graph transform *terraform.RootTransformer
2021/04/12 18:47:36 [TRACE] Completed graph transform *terraform.RootTransformer (no changes)
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch": entering dynamic subgraph
2021/04/12 18:47:36 [TRACE] dag/walk: visiting "docker_image.watch"
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch": starting visit (*terraform.NodePlannableResourceInstance)
2021-04-12T18:47:36.572+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/digitalocean/digitalocean/2.7.0/darwin_amd64/terraform-provider-digitalocean_v2.7.0 pid=19547
2021-04-12T18:47:36.573+0200 [DEBUG] plugin: plugin exited
2021/04/12 18:47:36 [TRACE] vertex "provider[\"registry.terraform.io/digitalocean/digitalocean\"] (close)": visit complete
2021/04/12 18:47:36 [TRACE] EvalReadStateDeposed: reading state for docker_container.traefik deposed object 6ee3527c
2021/04/12 18:47:36 [TRACE] UpgradeResourceState: upgrading state for docker_container.traefik from version 1 to 2 using provider "docker"
2021/04/12 18:47:36 [TRACE] GRPCProvider: UpgradeResourceState
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: reading state for docker_image.tlbc
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: no state present for docker_image.tlbc
2021/04/12 18:47:36 [DEBUG] refresh: docker_image.tlbc: no state, so not refreshing
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: reading state for docker_image.netstats
2021/04/12 18:47:36 [TRACE] EvalWriteState: using RefreshState for docker_image.tlbc
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: no state present for docker_image.netstats
2021/04/12 18:47:36 [TRACE] EvalWriteState: removing state object for docker_image.tlbc
2021/04/12 18:47:36 [DEBUG] refresh: docker_image.netstats: no state, so not refreshing
2021/04/12 18:47:36 [TRACE] EvalWriteState: using RefreshState for docker_image.netstats
2021/04/12 18:47:36 [TRACE] EvalWriteState: removing state object for docker_image.netstats
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: reading state for docker_image.traefik
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: reading state for docker_image.tlbc-testnet
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: no state present for docker_image.tlbc-testnet
2021/04/12 18:47:36 [TRACE] UpgradeResourceState: schema version of docker_image.traefik is still 0; calling provider "docker" for any other minor fixups
2021/04/12 18:47:36 [TRACE] GRPCProvider: UpgradeResourceState
2021/04/12 18:47:36 [DEBUG] refresh: docker_image.tlbc-testnet: no state, so not refreshing
2021/04/12 18:47:36 [TRACE] EvalWriteState: using RefreshState for docker_image.tlbc-testnet
2021/04/12 18:47:36 [TRACE] EvalWriteState: removing state object for docker_image.tlbc-testnet
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: reading state for docker_image.watch
2021/04/12 18:47:36 [TRACE] ReadResourceInstanceState: no state present for docker_image.watch
2021/04/12 18:47:36 [DEBUG] refresh: docker_image.watch: no state, so not refreshing
2021/04/12 18:47:36 [TRACE] EvalWriteState: using RefreshState for docker_image.watch
2021/04/12 18:47:36 [TRACE] EvalWriteState: removing state object for docker_image.watch
2021/04/12 18:47:36 [TRACE] Re-validating config for "docker_image.tlbc"
2021/04/12 18:47:36 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/04/12 18:47:36 [TRACE] Re-validating config for "docker_image.netstats"
2021/04/12 18:47:36 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/04/12 18:47:36 [TRACE] Re-validating config for "docker_image.tlbc-testnet"
2021/04/12 18:47:36 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/04/12 18:47:36 [TRACE] Re-validating config for "docker_image.watch"
2021/04/12 18:47:36 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: panic: assignment to entry in nil map
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: goroutine 87 [running]:
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.replaceLabelsMapFieldWithSetField(0x0, 0x1)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	github.com/terraform-providers/terraform-provider-docker/docker/label_migration.go:9 +0x17e
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.migrateContainerLabels(0x0, 0x1b8dec0)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	github.com/terraform-providers/terraform-provider-docker/docker/label_migration.go:16 +0x2f
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.resourceDockerContainer.func1(0x0, 0x1b80e00, 0xc000231120, 0xc0002f2160, 0x1b8dec0, 0xc0001146f0)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	github.com/terraform-providers/terraform-provider-docker/docker/resource_docker_container.go:29 +0x2b
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).upgradeJSONState(0xc00000ed08, 0x1, 0x0, 0xc0001aad80, 0xc0001146f0, 0x0, 0x0)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:395 +0xb7
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).UpgradeResourceState(0xc00000ed08, 0x1f10680, 0xc0002f4390, 0xc0004a6080, 0xc00000ed08, 0xc0002f4390, 0xc000222a48)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:270 +0x285
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_UpgradeResourceState_Handler(0x1d34b40, 0xc00000ed08, 0x1f10680, 0xc0002f4390, 0xc000117320, 0x0, 0x1f10680, 0xc0002f4390, 0xc00013af00, 0x1c)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3117 +0x214
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00043e160, 0x1f1ad40, 0xc000119800, 0xc0000c3f00, 0xc00068c3c0, 0x25359c0, 0x0, 0x0, 0x0)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	google.golang.org/grpc@v1.23.1/server.go:995 +0x482
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: google.golang.org/grpc.(*Server).handleStream(0xc00043e160, 0x1f1ad40, 0xc000119800, 0xc0000c3f00, 0x0)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	google.golang.org/grpc@v1.23.1/server.go:1275 +0xd34
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005316f0, 0xc00043e160, 0x1f1ad40, 0xc000119800, 0xc0000c3f00)
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	google.golang.org/grpc@v1.23.1/server.go:710 +0xa5
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-12T18:47:36.577+0200 [DEBUG] plugin.terraform-provider-docker_v2.11.0: 	google.golang.org/grpc@v1.23.1/server.go:708 +0xa5
2021-04-12T18:47:36.579+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/kreuzwerker/docker/2.11.0/darwin_amd64/terraform-provider-docker_v2.11.0 pid=19552 error="exit status 2"
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch (expand)": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.watch (expand)": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc-testnet": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.traefik": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_container.traefik (deposed 6ee3527c)": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc-testnet": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.watch-archive-tlbc (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] vertex "docker_image.traefik": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.watch-access-laika (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] vertex "docker_image.traefik": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.netstats": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.traefik (expand)": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc-testnet": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.netstats": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.traefik (expand)": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc-testnet (expand)": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc-testnet (expand)": visit complete
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.traefik (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc": visit complete
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.access-laika (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] vertex "docker_image.netstats": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc (expand)": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] vertex "docker_image.tlbc (expand)": visit complete
2021/04/12 18:47:36 [TRACE] vertex "docker_image.netstats (expand)": dynamic subgraph encountered errors
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.archive-tlbc (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] vertex "docker_image.netstats (expand)": visit complete
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.access-laika-netstats (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.archive-tlbc-netstats (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/kreuzwerker/docker\"].archive-tlbc (close)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/kreuzwerker/docker\"] (close)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/kreuzwerker/docker\"].access-laika (close)" errored, so skipping
2021/04/12 18:47:36 [TRACE] vertex "provider[\"registry.terraform.io/kreuzwerker/docker\"].archive-laika": visit complete
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.archive-laika (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.archive-laika-netstats (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "docker_container.watch-archive-laika (expand)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/kreuzwerker/docker\"].archive-laika (close)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/04/12 18:47:36 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/04/12 18:47:36 [INFO] backend/local: plan operation completed
2021-04-12T18:47:36.678+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.679+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:47:36.679+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:47:36.679+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:47:36.680+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-12T18:47:36.684+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/kreuzwerker/docker/2.11.0/darwin_amd64/terraform-provider-docker_v2.11.0 pid=19551
2021-04-12T18:47:36.684+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.684+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/kreuzwerker/docker/2.11.0/darwin_amd64/terraform-provider-docker_v2.11.0 pid=19554
2021-04-12T18:47:36.684+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.684+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/kreuzwerker/docker/2.11.0/darwin_amd64/terraform-provider-docker_v2.11.0 pid=19549
2021-04-12T18:47:36.684+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=19532
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=19541
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=19529
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin exited
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform pid=19544
2021-04-12T18:47:36.689+0200 [DEBUG] plugin: plugin exited

```

the log above talks about archive-laika. The tf looks like this:

```
provider "docker" {
  host    = "ssh://root@${digitalocean_droplet.archive-laika.ipv4_address}"
  alias   = "archive-laika"
}

resource "docker_container" "archive-laika" {
  provider          = docker.archive-laika
  image             = docker_image.tlbc-testnet.latest
  name              = "laika-node"
  restart           = "always"
  network_mode      = "host"
  publish_all_ports = true
  command = [
"xy"
  ]

  volumes {
    host_path      = "/home/yyy"
    container_path = "/data"
    read_only = false
  }
}

resource "docker_container" "archive-laika-netstats" {
  provider     = docker.archive-laika
  image        = docker_image.netstats.latest
  name         = "netstats"
  network_mode = "host"
  restart      = "always"
  env = [
    "WS_HOST=xxx",
    ....
  ]
}

resource "docker_container" "watch-archive-laika" {
  provider     = docker.archive-laika
  image        = docker_image.watch.latest
  name         = "watch"
  network_mode = "host"
  restart      = "always"
  command      = ["jsonrpc", "--riemann-host", "xxx", "--event-host-dwim"]
}

output "archive-laika" {
  value = {
    ip         = digitalocean_droplet.archive-laika.ipv4_address
    private_ip = digitalocean_droplet.archive-laika.ipv4_address_private
  }
}

```

### Terraform (and docker Provider) Version
Terraform v0.14.10
+ provider registry.terraform.io/digitalocean/digitalocean v2.7.0
+ provider registry.terraform.io/hashicorp/dns v3.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/kreuzwerker/docker v2.11.0

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #176

### CODE REVIEW

File: internal/provider/resource_docker_container_migrators.go [hunk 1]
```diff
@@ -908,6 +908,9 @@ func updateV0ToV1PortsOrder(is *terraform.InstanceState, meta interface{}) error
 }
 
 func replaceLabelsMapFieldWithSetField(rawState map[string]interface{}) map[string]interface{} {
+	if rawState == nil {
+		return rawState
```
Comment (compojoom) [inline internal/provider/resource_docker_container_migrators.go:912]: nitpicking: I would return nil, cause one normally expects that if something is equal nil, we afterwards assign a value and return that value. In this case since we are just protecting the rest of the function it would be a little more clear that we don't do anything by returning `return nil`. At least that's for me :)

Comment (suzuki-shunsuke) [reply internal/provider/resource_docker_container_migrators.go:912]: Thank you for your review.
It makes sense.

Comment (suzuki-shunsuke) [reply internal/provider/resource_docker_container_migrators.go]: Fixed a092c74

**Review by mavogel — APPROVED** [review]
